/**
 * Custom Font Example
 *
 * Demonstrates how to:
 * 1. Register custom fonts generated by E-Paper Font Generator
 * 2. Use custom fonts with WatcherDisplay
 * 3. Mix multiple fonts in a single display
 */

#include <WatcherDisplay.h>

// Include your custom fonts (generated by font_generator.py)
// You need to copy the generated .h and .cpp files to your project first
#include "fonts/FontMinecraft16.h"
#include "fonts/FontMinecraft24.h"
// Add more fonts as needed:
// #include "fonts/FontIBMPlex20.h"
// #include "fonts/FontRoboto24.h"

WatcherDisplay display;

void setup() {
    Serial.begin(115200);
    Serial.println("Custom Font Example");

    // Initialize display
    if (!display.begin()) {
        Serial.println("Display init failed!");
        return;
    }

    display.clear();

    // ========== REGISTER CUSTOM FONTS ==========

    // Method 1: Using macro (recommended)
    FONT_REGISTER("Minecraft", 16, FontMinecraft16);
    FONT_REGISTER("Minecraft", 24, FontMinecraft24);

    // Method 2: Using FontHandler directly
    display.getFontHandler().registerFont("Minecraft", 16, &FontMinecraft16);
    display.getFontHandler().registerFont("Minecraft", 24, &FontMinecraft24);

    // Add more fonts:
    // FONT_REGISTER("IBMPlex", 20, FontIBMPlex20);
    // FONT_REGISTER("Roboto", 24, FontRoboto24);

    // List all registered fonts (debug)
    display.getFontHandler().listFonts();

    // ========== DRAW WITH CUSTOM FONTS ==========

    // Draw title with custom font
    display.drawTextCustom(50, 10, "POMODORO TIMER", "Minecraft", 24, true);
    display.updateRegion(50, 10, 300, 30);

    delay(1000);

    // Draw body text with smaller custom font
    display.drawTextCustom(50, 60, "Time remaining:", "Minecraft", 16, true);
    display.drawNumberCustom(200, 60, 25, "Minecraft", 16, true);
    display.updateRegion(50, 60, 250, 25);

    delay(1000);

    // Mix custom and standard fonts
    display.drawTextCustom(50, 100, "Task:", "Minecraft", 16, true);
    display.drawText(110, 100, "Write Code", &Font16, true);
    display.updateRegion(50, 100, 250, 25);

    delay(1000);

    // Draw status with custom font
    display.fillRegion(50, 140, 150, 30, COLORED);
    display.drawTextCustom(70, 145, "RUNNING", "Minecraft", 16, false);
    display.updateRegion(50, 140, 150, 30);

    Serial.println("Example complete!");
}

void loop() {
    // Nothing to do
}
