[platformio]
default_envs = lilygo-t5-4.2

[env:lilygo-t5-4.2]
platform = espressif32
board    = lilygo-t5
framework = arduino
upload_speed = 921600
monitor_speed = 115200
lib_deps =
    zinggjm/GxEPD2 @ ^1.5.6
    adafruit/Adafruit GFX Library @ ^1.11.10
    fbiego/ESP32Time @ ^2.0.6
build_flags =
    -DDISPLAY_W=400
    -DDISPLAY_H=300
