#!/usr/bin/env python3
"""
WatcherDisplay Font Generator
Automatically converts all TTF/OTF fonts in ../fonts/input/ directory to C bitmap arrays
Generates standard sizes: 12, 14, 16, 18, 20, 24, 28, 32px
Output organized by font name in ../fonts/output/

Usage:
    cd lib/WatcherDisplay/tools
    python generate_all.py

Generated fonts will be placed in lib/WatcherDisplay/fonts/output/
"""

import os
import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

# Standard sizes to generate
STANDARD_SIZES = [12, 14, 16, 18, 20, 24, 28, 32]

# Paths relative to the tools directory
# fonts/input for source TTF/OTF files
# fonts/output for generated C++ files
SCRIPT_DIR = Path(__file__).parent
INPUT_DIR = str(SCRIPT_DIR.parent / "fonts" / "input")
OUTPUT_DIR = str(SCRIPT_DIR.parent / "fonts" / "output")


def sanitize_name(name):
    """Convert font filename to valid C identifier"""
    # Remove extension
    name = os.path.splitext(name)[0]
    # Remove spaces, hyphens
    name = name.replace(' ', '').replace('-', '').replace('_', '')
    # Ensure starts with letter
    if name[0].isdigit():
        name = 'Font' + name
    return name


def generate_font_bitmap(font_path, font_height, output_dir, font_base_name):
    """Generate single font size"""
    
    output_name = f"{font_base_name}{font_height}"
    
    try:
        font = ImageFont.truetype(font_path, font_height)
    except Exception as e:
        print(f"  ✗ Size {font_height}px: Failed to load - {e}")
        return False
    
    # Test canvas
    test_img = Image.new('1', (font_height * 3, font_height * 3), 1)
    test_draw = ImageDraw.Draw(test_img)
    
    # Measure width
    try:
        bbox_m = test_draw.textbbox((0, 0), 'M', font=font)
        char_width = bbox_m[2] - bbox_m[0]
    except Exception as e:
        print(f"  ✗ Size {font_height}px: Measurement failed - {e}")
        return False
    
    font_width = char_width
    width_bytes = (font_width + 7) // 8
    
    # Measure height bounds
    all_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789gjpqy!@#$%"
    min_y = 999
    max_y = -999
    
    for char in all_chars:
        try:
            bbox = test_draw.textbbox((0, 0), char, font=font)
            min_y = min(min_y, bbox[1])
            max_y = max(max_y, bbox[3])
        except:
            continue
    
    natural_height = max_y - min_y
    
    # Calculate y offset to center
    if natural_height <= font_height:
        y_offset = (font_height - natural_height) // 2 - min_y
    else:
        y_offset = -min_y
    
    # Generate bitmaps for ASCII 0x20-0x7E
    font_data = []
    
    for ascii_code in range(0x20, 0x7F):
        char = chr(ascii_code)
        
        img = Image.new('1', (font_width, font_height), 1)
        draw = ImageDraw.Draw(img)
        
        try:
            bbox = draw.textbbox((0, 0), char, font=font)
            char_pixel_width = bbox[2] - bbox[0]
            x_pos = (font_width - char_pixel_width) // 2
            draw.text((x_pos, y_offset), char, font=font, fill=0)
        except:
            pass
        
        # Convert to bytes
        char_bytes = []
        pixels = img.load()
        
        for y in range(font_height):
            for byte_col in range(width_bytes):
                byte_val = 0
                for bit in range(8):
                    x = byte_col * 8 + bit
                    if x < font_width:
                        if pixels[x, y] == 0:
                            byte_val |= (1 << (7 - bit))
                char_bytes.append(byte_val)
        
        font_data.append((char, char_bytes))
    
    # Write .cpp file
    cpp_filename = os.path.join(output_dir, f"{output_name}.cpp")
    
    try:
        with open(cpp_filename, 'w', encoding='utf-8') as f:
            f.write(f"""/**
  * @file    {output_name}.cpp
  * @brief   {font_height}px bitmap font
  * @note    Generated by E-Paper Font Generator
  *          Source: {os.path.basename(font_path)}
  *          Dimensions: {font_width}×{font_height}px
  *          Natural height: {natural_height}px
  */

#include "fonts.h"

const uint8_t {output_name}_Table[] = 
{{
""")
            
            for char, char_bytes in font_data:
                char_display = char if char.isprintable() and char != '\\' else f"0x{ord(char):02X}"
                f.write(f"\t// @{(ord(char) - 0x20) * len(char_bytes)} '{char_display}'\n")
                
                for row in range(font_height):
                    row_bytes = char_bytes[row * width_bytes:(row + 1) * width_bytes]
                    
                    visual = ""
                    for byte_val in row_bytes:
                        for bit in range(8):
                            visual += "#" if (byte_val & (1 << (7 - bit))) else " "
                    visual = visual[:font_width]
                    
                    f.write("\t")
                    for byte_val in row_bytes:
                        f.write(f"0x{byte_val:02X}, ")
                    f.write(f" // {visual}\n")
                
                f.write("\n")
            
            f.write(f"""}};\n
sFONT {output_name} = {{
  {output_name}_Table,
  {font_width}, /* Width */
  {font_height}, /* Height */
}};
""")
    except Exception as e:
        print(f"  ✗ Size {font_height}px: Write failed - {e}")
        return False
    
    # Write .h file
    h_filename = os.path.join(output_dir, f"{output_name}.h")
    guard_name = f"__{output_name.upper()}_H__"
    
    try:
        with open(h_filename, 'w', encoding='utf-8') as f:
            f.write(f"""/**
  * @file    {output_name}.h
  * @brief   {font_height}px bitmap font header
  */

#ifndef {guard_name}
#define {guard_name}

#ifdef __cplusplus
extern "C" {{
#endif

#include "fonts.h"

extern sFONT {output_name};

#ifdef __cplusplus
}}
#endif

#endif
""")
    except Exception as e:
        print(f"  ✗ Size {font_height}px: Header write failed - {e}")
        return False
    
    file_size = os.path.getsize(cpp_filename)
    print(f"  ✓ Size {font_height}px: {output_name}.cpp ({file_size:,} bytes)")
    return True


def process_font_file(font_path):
    """Process single font file - generate all standard sizes"""
    
    font_filename = os.path.basename(font_path)
    print(f"\n{'='*70}")
    print(f"Processing: {font_filename}")
    print(f"{'='*70}")
    
    # Create output subdirectory
    font_base_name = sanitize_name(font_filename)
    font_output_dir = os.path.join(OUTPUT_DIR, font_base_name)
    os.makedirs(font_output_dir, exist_ok=True)
    
    print(f"Output directory: {font_output_dir}")
    print(f"Base name: {font_base_name}")
    print()
    
    success_count = 0
    
    for size in STANDARD_SIZES:
        if generate_font_bitmap(font_path, size, font_output_dir, font_base_name):
            success_count += 1
    
    print()
    print(f"Generated {success_count}/{len(STANDARD_SIZES)} sizes successfully")
    
    return success_count > 0


def main():
    print("=" * 70)
    print("E-Paper Font Generator")
    print("=" * 70)
    print()
    
    # Check input directory
    if not os.path.exists(INPUT_DIR):
        print(f"ERROR: {INPUT_DIR}/ directory not found")
        print("Create it and place your TTF/OTF files there")
        sys.exit(1)
    
    # Find all font files
    font_files = []
    for ext in ['*.ttf', '*.otf', '*.TTF', '*.OTF']:
        font_files.extend(Path(INPUT_DIR).glob(ext))
    
    if not font_files:
        print(f"ERROR: No font files found in {INPUT_DIR}/")
        print("Place .ttf or .otf files in the input/ directory")
        sys.exit(1)
    
    print(f"Found {len(font_files)} font file(s):")
    for f in font_files:
        print(f"  - {f.name}")
    print()
    
    # Create output directory
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    # Process each font
    processed = 0
    for font_path in font_files:
        if process_font_file(str(font_path)):
            processed += 1
    
    print()
    print("=" * 70)
    print(f"Complete! Processed {processed}/{len(font_files)} fonts")
    print("=" * 70)
    print()
    print(f"Output location: {OUTPUT_DIR}/")
    print()
    print("Next steps:")
    print("  1. Browse ../fonts/output/ subdirectories")
    print("  2. Copy desired .cpp and .h files to your project's src/ directory")
    print("  3. Register fonts using FONT_REGISTER() macro in setup()")
    print("  4. Use fonts with display.drawTextCustom() or FONT_GET() macro")
    print()
    print("Example usage:")
    print('  FONT_REGISTER("Monocraft", 16, FontMonocraft16);')
    print('  display.drawTextCustom(x, y, "Hello", "Monocraft", 16, true);')


if __name__ == '__main__':
    main()
